name: todo_list_dart_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.9.2'

dependencies:
  cupertino_icons: 1.0.5
  flutter:
    sdk: flutter
  todo_list_dart_client:
    path: ../todo_list_dart_client

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
