name: todo_list_dart_core
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: 3.9.2

dependencies:
  freezed_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.6.0
  freezed: 3.2.3
